// Standard HTTP errors and helpers for MTG GPT middleware
export const ErrorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  REQUEST_TOO_LARGE: "REQUEST_TOO_LARGE",
  UNSUPPORTED_IMPORT_SOURCE: "UNSUPPORTED_IMPORT_SOURCE",
  INVALID_COLLECTION_EXPORT: "INVALID_COLLECTION_EXPORT",
  MISSING_REQUIRED_HEADER: "MISSING_REQUIRED_HEADER",
  INVALID_QUANTITY: "INVALID_QUANTITY",
  INVALID_SCRYFALL_ID: "INVALID_SCRYFALL_ID",
  CARD_RESOLUTION_AMBIGUOUS: "CARD_RESOLUTION_AMBIGUOUS",
  IMPORT_ALREADY_RUNNING: "IMPORT_ALREADY_RUNNING",
  IMPORT_TRANSACTION_FAILED: "IMPORT_TRANSACTION_FAILED",
  CARD_NOT_FOUND: "CARD_NOT_FOUND",
  INVALID_DECKLIST: "INVALID_DECKLIST",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

export function sendError(res, status, code, message, details = null) {
  return res.status(status).json({
    success: false,
    error: {
      code,
      message,
      ...(details ? { details } : {}),
    },
  });
}
